Repository JohnnySn0w/MoD, pull requests merged in 2019-04, with the labels that each got.

#42 Attack command
  DiscordBot/commands/dbCommands/dbRequests.js
  DiscordBot/commands/mud/attack.js
  DiscordBot/commands/mud/start.js
  DiscordBot/commands/mud/talk.js
  DiscordBot/player-stats.js
  DiscordBot/schemas/entities.js
  DiscordBot/schemas/entities.json
  DiscordBot/schemas/items.js
  DiscordBot/schemas/players.js
  DiscordBot/schemas/players.json
  DiscordBot/schemas/rooms.js
  DiscordBot/schemas/rooms.json
  databaseManager.js
  dbhandler.js
  package.json
Labels: RFR

#44 wording rephrases
  DiscordBot/commands/admin/dbRequests.js
  DiscordBot/commands/mud/attack.js
  DiscordBot/commands/mud/look.js
  DiscordBot/commands/mud/move.js
  DiscordBot/commands/mud/start.js
  DiscordBot/commands/mud/stats.js
  DiscordBot/commands/mud/talk.js
  DiscordBot/schemas/entities.json
  DiscordBot/schemas/items.json
  DiscordBot/schemas/rooms.json
Labels: WIP

#51 changes to config
  .gitignore
  DiscordBot/index.js
Labels: RFR, bug

#52 changed room id scheme
  DiscordBot/commands/admin/dbRequests.js
  DiscordBot/commands/mud/attack.js
  DiscordBot/commands/mud/look.js
  DiscordBot/commands/mud/move.js
  DiscordBot/commands/mud/start.js
  DiscordBot/commands/mud/talk.js
  DiscordBot/schemas/rooms.json
Labels: WIP

#55 Remove room ids v3
  DiscordBot/commands/admin/dbRequests.js
  DiscordBot/commands/mud/attack.js
  DiscordBot/commands/mud/look.js
  DiscordBot/commands/mud/move.js
  DiscordBot/commands/mud/start.js
  DiscordBot/commands/mud/talk.js
  DiscordBot/schemas/rooms.json
  package.json
  yarn.lock
Labels: RFR

#57 Loot
  DiscordBot/commands/mud/attack.js
  DiscordBot/commands/mud/inventory.js
  DiscordBot/commands/mud/stats.js
  DiscordBot/schemas/enemies.json
  DiscordBot/schemas/items.json
  self-bot.js
Labels: WIP

#60 refurbished and moved lag
  DiscordBot/commands/mud/attack.js
  DiscordBot/commands/mud/inventory.js
  DiscordBot/commands/mud/move.js
  DiscordBot/commands/mud/stats.js
  DiscordBot/schemas/players.json
  databaseManager.js
  dbhandler.js
  package.json
  yarn.lock
Labels: RFR

#58 Attack damage
  DiscordBot/commands/mud/attack.js
Labels: WIP

#61 Evolution of Combat
  DiscordBot/commands/mud/attack.js
  DiscordBot/globals.js
  dbhandler.js
Labels: RFR
